# Generated by Django 5.0.2 on 2026-01-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='email_show_page_path',
            field=models.CharField(blank=True, help_text="Comma-separated paths (e.g. 'grass' or 'grass,bark') to auto-trigger popup on these specific pages.", max_length=500, null=True),
        ),
    ]
