# Generated by Django 5.0.2 on 2026-01-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popups', '0002_sitesettings_email_show_page_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='email_offer_desc',
            field=models.TextField(default='Sign up now to get a free discount.', help_text='Description text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_offer_image',
            field=models.ImageField(blank=True, help_text='Banner image for the popup', null=True, upload_to='popups/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_offer_link',
            field=models.CharField(blank=True, help_text='URL when clicking image (Left side)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_offer_text',
            field=models.CharField(default='Exclusive Offer!', help_text='Headline text', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_show_desc',
            field=models.BooleanField(default=True, help_text='Show Description text in popup'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_show_name',
            field=models.BooleanField(default=True, help_text='Show Name field in popup'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email_show_page_path',
            field=models.CharField(blank=True, help_text="Comma-separated paths (e.g., 'grass' or 'grass,bark') to auto-trigger popup on these specific pages.", max_length=500, null=True),
        ),
    ]
