# Generated by Django 5.0.2 on 2026-01-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popups', '0003_sitesettings_email_offer_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralPopup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the popup (Internal Use)', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Is this popup currently active?')),
                ('target_pages', models.CharField(blank=True, help_text='Page slugs (comma separated) to auto-trigger popup. Leave empty to trigger everywhere via timer.', max_length=500, null=True)),
                ('delay_seconds', models.PositiveIntegerField(default=15, help_text='Delay in seconds before showing popup on target pages')),
                ('show_checkbox', models.BooleanField(default=False, help_text="Show 'Don't show again' checkbox?")),
                ('show_name', models.BooleanField(default=True, help_text="Show 'Name' input field?")),
                ('show_desc', models.BooleanField(default=True, help_text="Show 'Description' textarea field?")),
                ('title', models.CharField(help_text='Popup Title', max_length=200)),
                ('image', models.ImageField(blank=True, help_text='Banner image or illustration', null=True, upload_to='popups/')),
                ('link_url', models.CharField(blank=True, help_text='URL if clicking image acts as a link', max_length=200, null=True)),
                ('content', models.TextField(blank=True, help_text='HTML content of the popup body', null=True)),
                ('is_exit_intent', models.BooleanField(default=False, help_text='If checked, this popup acts as Exit Intent (shows when mouse leaves top)')),
            ],
        ),
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
