# Generated by Django 5.0.2 on 2026-01-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popups', '0004_generalpopup_delete_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalpopup',
            name='is_adblock_warning',
            field=models.BooleanField(default=False, help_text='Check if this is the AdBlock Warning popup'),
        ),
    ]
