# Generated by Django 5.0.2 on 2026-01-10 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popups', '0005_generalpopup_is_adblock_warning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalpopup',
            name='is_adblock_warning',
        ),
    ]
