# Generated by Django 5.0.2 on 2026-01-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popups', '0006_remove_generalpopup_is_adblock_warning'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalpopup',
            name='is_adblock_warning',
            field=models.BooleanField(default=False, help_text='Is this the AdBlock Warning popup?'),
        ),
        migrations.AlterField(
            model_name='generalpopup',
            name='delay_seconds',
            field=models.PositiveIntegerField(default=15, help_text='Delay in seconds for Email Collector.'),
        ),
        migrations.AlterField(
            model_name='generalpopup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='popups/'),
        ),
        migrations.AlterField(
            model_name='generalpopup',
            name='is_exit_intent',
            field=models.BooleanField(default=False, help_text='Is this an Exit Intent popup?'),
        ),
        migrations.AlterField(
            model_name='generalpopup',
            name='link_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='generalpopup',
            name='name',
            field=models.CharField(help_text='Internal Name (e.g. AdBlock Warning)', max_length=200),
        ),
        migrations.AlterField(
            model_name='generalpopup',
            name='target_pages',
            field=models.CharField(blank=True, help_text='Page slugs (comma separated) for Email Collector.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='source',
            field=models.CharField(default='manual', help_text='Source of subscription', max_length=50),
        ),
    ]
