# Generated by Django 5.0.2 on 2026-01-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popups', '0007_generalpopup_is_adblock_warning_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalpopup',
            name='is_adblock_warning',
        ),
        migrations.AlterField(
            model_name='generalpopup',
            name='delay_seconds',
            field=models.PositiveIntegerField(default=15, help_text='Delay in seconds for newsletter popup.'),
        ),
        migrations.AlterField(
            model_name='generalpopup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='generalpopup',
            name='is_exit_intent',
            field=models.BooleanField(default=False, help_text='Check if this is an Exit Intent popup'),
        ),
        migrations.AlterField(
            model_name='generalpopup',
            name='name',
            field=models.CharField(help_text='Internal Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='generalpopup',
            name='target_pages',
            field=models.CharField(blank=True, help_text="Page slugs (e.g. 'grass,bark') to show newsletter popup immediately.", max_length=500, null=True),
        ),
    ]
