# Generated by Django 5.0.2 on 2026-01-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popups', '0008_remove_generalpopup_is_adblock_warning_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalpopup',
            name='delay_seconds',
            field=models.PositiveIntegerField(default=15, help_text='Delay in seconds before showing popup on target pages'),
        ),
        migrations.AlterField(
            model_name='generalpopup',
            name='image',
            field=models.ImageField(blank=True, help_text='Banner image or illustration', null=True, upload_to='popups/'),
        ),
        migrations.AlterField(
            model_name='generalpopup',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this popup currently active?'),
        ),
        migrations.AlterField(
            model_name='generalpopup',
            name='is_exit_intent',
            field=models.BooleanField(default=False, help_text='If checked, this popup acts as Exit Intent (shows when mouse leaves top)'),
        ),
        migrations.AlterField(
            model_name='generalpopup',
            name='link_url',
            field=models.CharField(blank=True, help_text='URL if clicking image acts as a link', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='generalpopup',
            name='name',
            field=models.CharField(help_text='Name of the popup (Internal Use)', max_length=200),
        ),
        migrations.AlterField(
            model_name='generalpopup',
            name='target_pages',
            field=models.CharField(blank=True, help_text='Page slugs (comma separated) to auto-trigger popup. Leave empty to trigger everywhere via timer.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='source',
            field=models.CharField(default='manual', help_text='Source of subscription (e.g. exit_intent, manual)', max_length=50),
        ),
    ]
