# Generated by Django 5.0.2 on 2026-01-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('sidebar_top', 'Sidebar Top'), ('left_bar', 'Left Bar (Above Content)'), ('top_bar', 'Top Bar (Below Nav)'), ('bottom_bar', 'Bottom Bar (Above Footer)')], help_text='Select where this ad will appear on the site.', max_length=20, unique=True)),
                ('image', models.ImageField(upload_to='ads/')),
                ('link', models.URLField(blank=True, help_text='Optional: URL to open when clicked', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
